Initial proposal for visual redesign
osu-tournament-rating/otr-wiki pull request #16
Opened 2024-02-25 06:10 UTC by myssto

- Use [osu!wiki](https://osu.ppy.sh/wiki/en/Main_page)-like table design for landing
- Add contributors section
- Start documentation of API
  - Object structure
  - Endpoints
  - Changelog (mainly for breaking changes)

Reviewers please do suggest any formatting changes and wording changes. The redesign is meant to be more of a proof of concept so we have a baseline to work off of going forward.

Going forward I will 100% be splitting my pulls into more digestible chunks, but considering that I chose the mistake of tackling several tasks at once (some of which depend on others), I'm leaving this one as is.

Closes #13

2024-02-25 21:44 UTC, hburn7 requested changes
Really great work overall, but some changes do need to be made. I kind of stopped reviewing API-specific code after a while because we have a lot to clean up there. Once changes are applied, please re-request my review and I'll thoroughly look through all of the API endpoints. Let me know here with any questions since not all of the endpoints are documented.

2024-02-25 21:44 UTC, hburn7 commented on api/README.md
> +Welcome to the documentation of the otr-api. You can use this API to interact with o!TR and obtain various information about osu! tournaments and those who play them.
```suggestion
Welcome to the documentation of the o!TR API project. You can use this API to obtain various information about osu! tournaments and those who play them. Please use the API with good intentions!
```

2024-02-25 21:44 UTC, hburn7 commented on api/README.md
> +At the moment, consider this documentation to be a permanent work in progress as we continue to refine o!TR while working towards an official release.
```suggestion
At the moment, consider this documentation to be in a state of constant evolution as we continue to refine our systems during this pre-release phase.
```

2024-02-25 21:44 UTC, hburn7 commented on api/README.md
> +If you encounter errors in this documentation or in the API, please check the [issues](https://github.com/osu-tournament-rating/otr-api/issues) section of the API repository. Alternatively you can br
```suggestion
If you encounter errors in this documentation or in the API, please check the [issues](https://github.com/osu-tournament-rating/otr-api/issues) section of the API repository for any existing bugs. If you don't find an existing issue, feel free to make one yourself! When in doubt, err on the side of issue creation.
```

2024-02-25 21:44 UTC, hburn7 commented on api/endpoints/matches/en.md
> +});
Everything here should be `camelCase`

2024-02-25 21:44 UTC, hburn7 commented on api/endpoints/matches/en.md
> +Http Response ( 200 | 400 | 401 )
Write `HTTP` instead
```suggestion
HTTP Response ( 200 | 400 | 401 )
```

2024-02-25 21:44 UTC, hburn7 commented on api/endpoints/matches/en.md
> +Setting this to true will verify that the `submitterid` is an ( **ADMIN** ) user. Will result in a 401 if not
Language should be consistent and more direct with direct references to variables and adding `code marks`. `camelCase` should be used when demonstrating most API query functions and responses. I also don't know how we should be writing user scopes here, but I have corrected the scope from admin to verifier. Scopes should always be identical in reference to [this page](https://github.com/osu-tournament-rating/otr-wiki/blob/master/api/scopes/en.md), including casing. We should definitely add a separate page specifically describing all of these documentation quirks so we can remain consistent when documenting.

```suggestion
Setting `verified` to `true` will assert that the `submitterId` has the ( **verifier** ) scope.
```

Instead of saying `Will result in a 401`, we should separately document response codes in a more concrete fashion.

This comment applies to all API documentation in this PR.

2024-02-25 21:44 UTC, hburn7 commented on api/endpoints/matches/en.md
> +| { ? } | integer[] |
When an endpoint returns any generic collection, the field is unnamed. I imagine this is a fine way to indicate this, but just so you know.

2024-02-25 21:44 UTC, hburn7 commented on api/endpoints/matches/en.md
> +fetch("https://api.otr.xyz/matches/batch", {
Endpoint incorrect. Consider defining a root once so we don't have to type this url over and over.

```suggestion
fetch("https://api.otr.stagec.xyz/matches/batch", {
```

2024-02-25 21:44 UTC, hburn7 commented on api/endpoints/matches/en.md
> +Http Response ( 200 | 401 )
Technically this does not return a `401`. `429` is returned by the API middleware if the user has insufficient permissions to execute this command.

I think it'd be best to document middleware results (such as `429`) once somewhere important, then omit them at the endpoint level. 

Adjust anywhere else an implied 401 is used without explicit documentation / where the function does not ever return `BadRequest()`.

2024-02-26 06:23 UTC, myssto commented on api/endpoints/matches/en.md
> +Setting this to true will verify that the `submitterid` is an ( **ADMIN** ) user. Will result in a 401 if not
> Language should be consistent and more direct with direct references to variables and adding `code marks`.

Agree

> `camelCase` should be used when demonstrating most API query functions and responses.

Also agree, I wasn't initially sure how certain fields translated from the api code to fields in the responses. In the code all variables for query parameters and body parameters are `camelCase`, but all fields in the DTOs are `PascalCase`. I understand they all get converted to `camelCase` regardless?

> I also don't know how we should be writing user scopes here, but I have corrected the scope from admin to verifier. Scopes should always be identical in reference to [this page](https://github.com/osu-tournament-rating/otr-wiki/blob/master/api/scopes/en.md), including casing.

Yep this was all written out before you did any documentation on scopes and I was purposefully trying to keep it vague awaiting the OAuth migration

> We should definitely add a separate page specifically describing all of these documentation quirks so we can remain consistent when documenting.

I'll open up an issue about wiki meta docs then, don't know if it would belong in this pull

2024-02-26 06:25 UTC, myssto commented on api/endpoints/matches/en.md
> +fetch("https://api.otr.xyz/matches/batch", {
Will definitely define a root. I actually just took a stab and guessed at the domain so I guess I was pretty close lol

2024-02-26 06:27 UTC, myssto commented on api/endpoints/matches/en.md
> +Http Response ( 200 | 401 )
Good idea, I'll open a separate issue for middleware responses then.

2024-02-26 06:28 UTC, myssto commented on api/endpoints/matches/en.md
> +| { ? } | integer[] |
👍

2024-02-26 06:39 UTC, myssto commented on README.md
> +      The o!TR website is the main access point of the platform (blah)(blah)(blah)(blah)(blah)(blah)
Just so you know, traditional markdown formatting doesn't work inside of HTML elements. Therefore that embedded link would have to be written `<a href=https://otr.stagec.xyz/unauthorized>o!TR website</a>` and the last sentence would have to be wrapped in `<i></i>` tags for italics.

2024-02-26 06:44 UTC, myssto commented on README.md
> +      Twitter • Discord • Github • Website
Glossary was an idea to do something similar to the [osu!wiki sitemap](https://osu.ppy.sh/wiki/en/Sitemap). I thought it would be worth to include a straightforward list of links to all docs on the wiki, but I can see how it defeats the purpose of all the nice formatting. I'll leave this one up to you

2024-02-26 07:22 UTC, myssto commented on README.md
> +      Twitter • Discord • Github • Website
Also I think it might be worth moving the FAQ out of `/algorithm` and giving it a dedicated spot. If we do that I'm not sure what would take its place in `/algorithm` though.

2024-02-26 08:15 UTC, myssto commented on README.md
> +      Find answers to frequently asked questions here! Have a question not answered here on the wiki, or want to suggest an improvement? Join the discord!</br></br>
Linked github discussion pages for each repo, I think it makes the most sense?

2024-02-27 10:05 UTC, myssto commented
I believe this batch of changes covers everything discussed.

Most importantly, I created `/api/endpoints/README.md` which currently documents the base URL, accept header, list of documented routes, and a breakdown of the formatting for endpoints.

Specifically reviewers please look to `/api/endpoints/README.md#scopes`. I believe this is probably the most efficient way of listing scopes going forward. Instead of listing admin and system for every endpoint, we can imply that they will always be accepted.

2024-02-28 00:44 UTC, hburn7 requested changes
I haven't scrutinized the documentation itself, assuming its correct. Addressed some grammar and formatting issues.

2024-02-28 00:44 UTC, hburn7 commented on api/endpoints/README.md
> +- `text/json`
are you sure? I'm pretty sure the API only expects JSON (and if it doesn't, we should probably fix that)

2024-02-28 00:44 UTC, hburn7 commented on api/endpoints/matches/en.md
>  ### Convert a List of Match Ids to Match Objects
Capitalization is kinda all over the place. I'd capitalize the first word & class names only. Check all the grammar in similar headings.

2024-02-28 00:49 UTC, myssto commented on api/endpoints/README.md
> +- `text/json`
Swagger seems to think that all three of those are valid /shrug. Unless that's just a product of having some development specific things enabled but I couldn't find evidence otherwise

2024-02-28 00:51 UTC, hburn7 commented on api/endpoints/README.md
> +- `text/json`
Alright. Just list json for now anyway.

2024-02-28 00:51 UTC, myssto commented on api/endpoints/matches/en.md
>  ### Convert a List of Match Ids to Match Objects
All of the headings are in [title case](https://apastyle.apa.org/style-grammar-guidelines/capitalization/title-case), save for  words like `Ids` which would count as proper in this context I believe

2024-02-28 00:59 UTC, hburn7 commented on api/endpoints/matches/en.md
>  ### Convert a List of Match Ids to Match Objects
Ah ok, as long as there is a consistent scheme, that's fine.

2024-03-02 02:47 UTC, cytusine0 reviewed
Skimmed through and noted down some small suggestions, though I didn't look carefully at the logic of how any of the API stuff actually works.

2024-03-02 02:47 UTC, cytusine0 commented on README.md
> +      <a href="algorithm/tournaments.md">FAQ</a> •
```suggestion
      <a href="algorithm/README.md">FAQ</a> • 
```
Linking here would be more general for rating-related questions.

2024-03-02 02:47 UTC, cytusine0 commented on README.md
> +      The rating system utilizes quite a bit of complex math to perform calculations. For those curious, we break down the process and rationale in detail.
```suggestion
      The rating system makes use of some complicated mathematics to analyze tournament data. For those curious, we break down the process and describe the rationale here.
```

2024-03-02 02:47 UTC, cytusine0 commented on README.md
> +      <a href="algorithm/tournaments.md">How We Handle Tournaments</a>
```suggestion
      <a href="algorithm/tournaments.md">Collecting Tournament Data</a>
```

2024-03-02 02:47 UTC, cytusine0 commented on api/endpoints/matches/en.md
> +  "teamSize": 8,
```suggestion
  "teamSize": 4,
```
🤓

2024-03-02 02:47 UTC, cytusine0 commented on api/endpoints/players/en.md
> +Desired gamemode
Would we want to clarify which integer corresponds to which gamemode? This is particularly relevant if we separate out 4k and 7k as separate modes (which might be numbers "3" and "4", I'm not sure).

2024-03-02 02:47 UTC, cytusine0 commented on api/objects/en.md
> +Represents a mapping of the otr match id to it's respective osu! match id
```suggestion
Represents a mapping of the o!TR match id to its respective osu! match id
```
For the record I am not looking that carefully at the actual content, just the funny small things :)

2024-03-03 02:44 UTC, myssto commented on api/endpoints/players/en.md
> +Desired gamemode
There is an [issue](https://github.com/osu-tournament-rating/otr-api/issues/129) opened on the API about changing `mode` to `ruleset`, in which case this would read "`ruleset` Ruleset" and `Ruleset` would have an entry in the Object Structures page.

2024-03-03 09:41 UTC, myssto commented on api/endpoints/README.md
> +- `text/json`
Actually, this is [intended behavior](https://learn.microsoft.com/en-us/aspnet/core/web-api/advanced/formatting?view=aspnetcore-8.0#content-negotiation-2)

2024-03-06 01:44 UTC, hburn7 commented
One last change before we merge. Please move:

- `objects/en.md` to `/usage/objects/en.md`
- `endpoints/en.md` to `/usage/endpoints/en.md`

Replace the `README.md` file with the following:
```
# o!TR API
Welcome to the documentation of the o!TR API project. You can use this API to obtain data on human-verified osu! tournaments and tournament players. Please, use the API for good!

At the moment, consider this documentation to be in a state of constant evolution as we continue to refine our systems during this pre-release phase.

If you encounter errors in this documentation or in the API, please check the [issues](https://github.com/osu-tournament-rating/otr-api/issues) section of the API repository for any existing bugs. If you don't find an existing issue, feel free to make one yourself! When in doubt, err on the side of issue creation.

## Table of Contents
<ol type="1">
  <li>Development</li>
  <ol>
    <li><a href="development/setup/en.md">Setup</a></li>
  </ol>
  <li>Usage</li>
  <ol>
    <li><a href="usage/authorization/en.md">OAuth Client Authorization Flow</a></li>
    <li><a href="usage/scopes/en.md">API Scopes</a></li>
    <li><a href="usage/endpoints/en.md">Endpoints</a></li>
    <li><a href="usage/objects/en.md">Response Objects</a></li>
  </ol>
</ol>

```

2024-03-06 02:58 UTC, merged