Add api setup instructions
osu-tournament-rating/otr-wiki pull request #18
Opened 2024-02-25 13:06 UTC by myssto

Add api setup documentation for development

90% finished, need clarification on `JWT.Audience` and `Auth` fields of appsettings

Included a mention of a "demo database" that was previously discussed and the commands to utilize it once we create it.

Feels like it is missing something to me? Maybe ending notes on how to build, run, and run tests?

Closes #7

2024-02-25 13:08 UTC, myssto commented
Also held off on editing root readme for now until #16 is discussed more

2024-02-25 22:00 UTC, hburn7 requested changes
Let's come back after a round of fixes 👍🏼

2024-02-25 22:00 UTC, hburn7 commented on api/development/en.md
> +The `Audience` field refers to the frontend webserver. You can set this to `"localhost:3000"`.
```suggestion
The `Audience` field refers to the intended recipient of the JWT. You can set this to any string for development purposes, but in production should be the intended resource server, such as `https://your.production.api.url`
```

2024-02-25 22:46 UTC, myssto commented
Holy writing this stuff at 4 am and then not proofreading it goes so hard 🔥

2024-02-25 23:15 UTC, hburn7 commented
Yeah, let's do some more proofing before PRing 😅

2024-02-26 05:17 UTC, myssto commented on api/development/en.md
> +This document will serve as a guide on how to setup a local development environment for the o!TR API.
Fixed this instance, and tried to edit a few more lines as well. See lines 30, 42, 86

2024-02-26 05:18 UTC, myssto commented on api/development/en.md
> +docker run --name {CONTAINER_NAME} -e POSTGRES_PASSWORD {PASSWORD} -p 5432:5432 -d postgres
Fixed all instances

2024-02-26 05:22 UTC, myssto commented on api/development/en.md
> +We have curated a demo database with a few years of tournament data from popular tournaments like OWC. You can choose to use this sample data over starting with an empty database if you wish. You can
Removed `(Optional)` text and added a warning about not having demo ready currently. Improved clarity of the existing paragraph.

2024-02-26 05:24 UTC, myssto commented on api/development/en.md
> +`"Server=localhost;Port=5432;User Id=postgres;Password=otrdev;Include Error Detail=true;"`
Were you referring to only the ConnectionStrings section here, or all of the sections? I understand this one is most important but breaking them up would probably not look great.

2024-02-26 05:24 UTC, myssto commented on api/development/en.md
> +The `Key` field is the secret the API uses to encode and decode Jason Web Tokens. You can set this to any random string.
omegalul

2024-02-26 05:27 UTC, myssto commented on api/development/en.md
> +Note that currently the config requires both a v1 osu! API key as well as v2 oath credentials, however the use of the v1 API will be phased out at some point. When creating the oath client, set the r
How I managed to use the term `oath` instead of OAuth on two different occasions is shocking

2024-02-26 05:32 UTC, myssto commented
Touched on all review points. Still need clarification on the last section of the config (Auth). Not sure if those fields are subject to change with [#110](https://github.com/osu-tournament-rating/otr-api/pull/110) from `otr-api` or not and I don't remember discussing them too much when we went over setup.

2024-02-28 00:23 UTC, hburn7 requested changes

2024-02-28 00:23 UTC, hburn7 commented on api/development/en.md
> +### Setting up a PostgreSQL Container
```suggestion
### Setting up a PostgreSQL Database
```

2024-02-28 00:23 UTC, hburn7 commented on api/development/en.md
> +The API requires a valid PostgreSQL connection to function. The easiest way to accomplish this is through [Docker](https://www.docker.com/).
```suggestion
The API requires a connection to a PostgreSQL database in order to function. The easiest way to accomplish this is through a [Docker](https://www.docker.com/) container.
```

2024-02-28 00:23 UTC, hburn7 commented on api/development/en.md
> +docker pull postgres
Technically this isn't a necessary step as `docker run` does this automatically.

2024-02-28 00:23 UTC, hburn7 commented on api/development/en.md
> +docker run -name otr-postgres-dev -e POSTGRES_PASSWORD=<some_password> -p 5432:5432 postgres
```suggestion
docker run -d -p 5432:5432 --name otr-postgres-dev -e POSTGRES_PASSWORD=<some_password> postgres
```

2024-02-28 00:23 UTC, hburn7 commented on api/development/en.md
> +We curated a demo database containing several years of data from well-known tournaments like OWC. You can download the SQL file from [here](). Once downloaded, execute the following commands.
```suggestion
*Note: The o!TR Demo Database is not available to the public at this time. This document will be updated once we have a public resource.*
```

2024-02-28 00:23 UTC, hburn7 commented on api/development/en.md
> +With your PostgreSQL setup and dependencies ready, you can now configure and build the API.
Prefer neutral language (remove second-person phrasing):

```suggestion
With a fresh PostgreSQL database instance and other required frameworks installed, the API can now be built and configured.
```

2024-02-28 00:23 UTC, hburn7 commented on api/development/en.md
> +Currently the configuration requires both an osu! API v1 key and v2 OAuth2 credentials, however the use of the v1 API will be phased out very soon. When creating the OAuth2 client, the redirect URL i
```suggestion
Currently the configuration requires both an osu! API v1 key and v2 OAuth2 credentials, however the use of the v1 API will be phased out very soon. When creating the OAuth2 client, the redirect URL is optional. If testing alongside `otr-web`, set the redirect URL to `http://localhost:3000/auth`.
```

2024-02-28 00:23 UTC, hburn7 commented on api/development/en.md
> +The `Key` field is the secret the API uses to encode and decode JSON Web Tokens. You can set this to any string.
```suggestion
The `Key` field is the secret the API uses to encode and decode JSON Web Tokens. This can be set to any string.
```

2024-02-28 00:23 UTC, hburn7 commented on api/development/en.md
> +The `Audience` field refers to the intended recipient of the JWT. You can set this to any string for development purposes, but in production should be the intended resource server, such as `https://y
```suggestion
The `Audience` field refers to the intended recipient of the JWT. This can be set to any string for development purposes, but in production should be the intended resource server, such as `https://some.production.api.url`.
```

2024-02-28 00:23 UTC, hburn7 commented on api/development/en.md
> +Need more information
```suggestion
```

We can add this in later, no point in PRing something unfinished.

2024-02-28 13:00 UTC, bugg86 approved these changes

2024-02-28 13:38 UTC, hburn7 commented on api/development/en.md
> +#### ConnectionStrings
```suggestion
#### Connection String
```

2024-02-28 21:03 UTC, hburn7 approved these changes

2024-02-28 21:05 UTC, hburn7 commented on api/development/en.md
> +`"Server=localhost;Port=5432;User Id=postgres;Password=otrdev;Include Error Detail=true;"`
I think I was saying this string example should be put into the actual config example. But, things are fine as they are now.

2024-02-29 02:18 UTC, merged