OAuth documentation
osu-tournament-rating/otr-wiki pull request #25
Opened 2024-03-06 21:27 UTC by hburn7

Adds documentation for:

- OAuth /authorize and /refresh endpoints
- Ratelimit and terms of use
- How to use the credentials after authorizing.

2024-03-12 02:13 UTC, myssto requested changes
Request again after some changes. Just small things for consistency's sake.

2024-03-12 02:13 UTC, myssto commented on api/usage/objects/en.md
> +### OAuth Response
```suggestion
### OAuthResponse
```
All objects use their exact class name (without DTO suffix if applicable)

2024-03-12 02:13 UTC, myssto commented on api/usage/endpoints/oauth/en.md
> +Returns [OAuth Response](/api/usage/objects/en.md#oauth-response)
```suggestion
Returns [OAuth Response](/api/usage/objects/en.md#oauthresponse)
```

2024-03-12 02:13 UTC, myssto commented on api/usage/endpoints/oauth/en.md
> +Returns [OAuth Response](/api/usage/objects/en.md#oauth-response), containing a new `accessToken`.
```suggestion
Returns [OAuth Response](/api/usage/objects/en.md#oauthresponse), containing a new `accessToken`.
```

2024-03-12 02:13 UTC, myssto commented on api/usage/objects/en.md
> +| accessToken | string | This code is used to authorize requests. In all API requests, construct your `Authorization` header as such: `Authorization: Bearer <accessToken>`
```suggestion
| accessToken | string | This code is used to authorize requests. In all API requests, construct your `Authorization` header as such: `Authorization: Bearer <accessToken>` |
```

2024-03-12 02:13 UTC, myssto commented on api/usage/objects/en.md
> +| refreshToken | string | Used by
```suggestion
| refreshToken | string | Used to obtain a new `accessToken` |
```

2024-03-12 02:13 UTC, myssto commented on api/usage/objects/en.md
> +| accessExpiration | integer |
```suggestion
| accessExpiration | integer | Expiration of the `accessToken` in seconds |
```

2024-03-12 02:38 UTC, hburn7 commented on api/usage/endpoints/oauth/en.md
> +Returns [OAuth Response](/api/usage/objects/en.md#oauth-response), containing a new `accessToken`.
Should the link here be written as [OAuthResponse](...) based on your other comment?

2024-03-12 02:40 UTC, hburn7 commented on api/usage/objects/en.md
> +| accessExpiration | integer |
I forgot to fill these in clearly, good catch.

2024-03-12 02:41 UTC, myssto commented on api/usage/endpoints/oauth/en.md
> +Returns [OAuth Response](/api/usage/objects/en.md#oauth-response), containing a new `accessToken`.
Yep, good catch

2024-03-22 03:29 UTC, myssto approved these changes

2024-03-22 18:44 UTC, merged